# Generated by Django 4.0.4 on 2022-05-24 18:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=64, verbose_name='Marka roweru:')),
                ('model', models.CharField(max_length=64, verbose_name='Model roweru:')),
                ('type', models.IntegerField(choices=[(1, 'rower szosowy'), (2, 'MTB'), (3, 'GRAVEL'), (4, 'dowolny rower')])),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.IntegerField(choices=[(1, 'rower szosowy'), (2, 'MTB'), (3, 'GRAVEL'), (4, 'dowolny rower')])),
            ],
        ),
        migrations.CreateModel(
            name='Cyclist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('region', models.IntegerField(choices=[(1, 'rower szosowy'), (2, 'MTB'), (3, 'GRAVEL'), (4, 'dowolny rower')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship_name', models.IntegerField(choices=[(1, 'rower szosowy'), (2, 'MTB'), (3, 'GRAVEL'), (4, 'dowolny rower')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=128, verbose_name='Nazwa wydarzenia:')),
                ('event_type', models.IntegerField(choices=[(1, 'wyścig'), (2, 'trening'), (3, 'coffee ride')])),
                ('limit', models.IntegerField(blank=True, verbose_name='Ilość miejsc:')),
                ('distance', models.FloatField()),
                ('route_description', models.TextField()),
                ('date', models.DateTimeField()),
                ('start', models.CharField(max_length=128)),
                ('finish', models.CharField(max_length=128)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling_events_app.category')),
                ('event_creator', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_participant', models.ManyToManyField(to='Cycling_events_app.cyclist')),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cycling_events_app.region')),
            ],
        ),
    ]
