# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycling_events_app', '0003_alter_event_event_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='region_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cycling_events_app.region'),
        ),
    ]
