# Generated by Django 4.0.2 on 2022-05-25 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cycling_events_app', '0005_alter_region_voivodeship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.IntegerField(blank=True, choices=[(1, 'rower szosowy'), (2, 'MTB'), (3, 'GRAVEL'), (4, 'dowolny rower')], null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cyclist',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_participant',
            field=models.ManyToManyField(to='Cycling_events_app.Profile'),
        ),
    ]
