# Generated by Django 4.0.2 on 2022-06-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cycling_events_app', '0006_profile_delete_cyclist_alter_event_event_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cycling_events_app.bike'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'mężczyzna'), ('F', 'kobieta')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.IntegerField(blank=True, choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], null=True),
        ),
    ]
