# Generated by Django 4.0.2 on 2022-06-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cycling_events_app', '0007_bike_image_profile_bike_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='type',
            new_name='bike_type',
        ),
    ]
