# Generated by Django 4.0.2 on 2022-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cycling_events_app', '0008_rename_type_bike_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
